### PR TITLE
Address open issues to resolve #23

### LINKED ISSUE #23: Wrangle GO NO-GO for Build 2021 release
GO NO-GO CRITERIA for offer with Preview creation at “May 24, 2021, 12:52:34 PM UTC
Preview creation.”
I suggest we need a GO NO-GO from the following stakeholders before clicking Go live.
@rk
@charters
@Reza Rahman (Microsoft)
@shane-orourke
@Ed Burns (Microsoft)

### PR DESCRIPTION
**Pull request by edburns**
modified:   pom.xml

Signed-off-by: Ed Burns <edburns@microsoft.com>

### CODE REVIEW

**Comment by edburns** [comment]
Resolves [gh-ibm-image-15](https://github.com/WASdev/azure.websphere-traditional.image/issues/15).

**Comment by edburns** [comment]
Hello @git4rk I kindly request you not merge this until I inform you that the **Publish in progress** has sufficiently completed.

**Comment by edburns** [comment]
This PR addresses all issues related to #23 .

**Comment by majguo** [comment]
Hello @git4rk Could you pls merge this PR since the code changes have already passed the testing and been rolled out to the official Azure marketplace offer? Thanks.

**Review by git4rk — APPROVED** [review]

**Pull request merged**
