### PR TITLE
Add pipeline to build artifact

### LINKED ISSUE #76: Create CI/CD pipeline that creates `azure.websphere-traditional.cluster-N.N.N-arm-assembly.zip` as a build artifact

### PR DESCRIPTION
**Pull request by zhengchang907**
**Add pipeline to automate artifact building for offer publish**

Step-by-step guidance:
* Use following command to trigger the pipeline
```bash
PERSONAL_ACCESS_TOKEN={your personal token}
REPO_NAME=WASdev/azure.websphere-traditional.cluster
curl --verbose -XPOST -u "WASdev:${PERSONAL_ACCESS_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/${REPO_NAME}/actions/workflows/package.yaml/dispatches --data '{"ref": "master"}'
```
* Go to Cluster Repo's action page: https://github.com/WASdev/azure.websphere-traditional.cluster/actions
* Select `Package ARM` under 'All workflows', click on the latest run.
* At the bottom of the action run page, click the artifact and download it for offer publish

Verified in forked repo: https://github.com/zhengchang907/azure.websphere-traditional.cluster/actions/runs/999902501

resolve #76 

[Creating a personal access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token)

Signed-off-by: Zheng Chang <zhengchang@microsoft.com>

### CODE REVIEW

**Comment by zhengchang907** [comment]
close issue #76

**Comment by git4rk** [comment]
@Zheng Chang Is the `PERSONAL_ACCESS_TOKEN` mentioned in the PR a real working token? We should not put tokens in the code/comment. Please remove it and add a comment on how to get that token.

**Comment by zhengchang907** [comment]
@git4rk Sorry I misplaced it in the PR description, it's remove and I added the link to creating personal access token guidance.

**Comment by majguo** [comment]
@git4rk Could you pls take a look and merge the PR if it looks good for you? Thanks.

**Review by git4rk — APPROVED** [review]

**Pull request merged**
